### ISSUE TITLE
fatal error: Cannot reach this branch

### ISSUE THREAD

**Issue by matiaskorhonen** [36Kr-Mobile/StatusBarNotificationCenter#1]
I'm trying to display a notification based on Reachability (using the [NSNotification approach](https://github.com/tonymillion/Reachability#in-swift-1)) changes but my app crashes every time on [line 202 of StatusBarNotificationCenter.swift](https://github.com/36Kr-Mobile/StatusBarNotificationCenter/blob/1.0.1/Pod/Notification%20Center/StatusBarNotificationCenter.swift#L202)

```
fatal error: Cannot reach this branch: file /Users/matt/Programming/piranhas-ios/Carthage/Checkouts/StatusBarNotificationCenter/Pod/Notification Center/StatusBarNotificationCenter.swift, line 202
```

I've wrapped the `showStatusBarNotificationWithMessage` calls in a `dispatch_async` block so they should be getting called on the UI thread, but obviously something is going wrong so that isn't helping

``` swift
// … snip …

dispatch_async(dispatch_get_main_queue()) { () -> Void in
    StatusBarNotificationCenter.showStatusBarNotificationWithMessage(message,
        forDuration: duration,
        withNotificationCenterConfiguration: self.sbnConfiguration,
        andNotificationLabelConfiguration: labelConfiguration
    )
}
```

**Comment by inatu** [comment]
Just like I have mentioned, the notification display rely on baseWindow, that is the window you want to display the notification on, i use it to calculate some geometry information, could you please set a break point in  line 199 of StatusBarNotificationCenter.swift, and po notificationCenterConfiguration, you can also track the backtrace, and find the problem. But I think the problem maybe because the notificationCenterConfiguration is set to nil too early, you should also know that this library is implemented in a notification basis, I just set it to nil when the notification showing process is done, so you shouldn't keep a reference to it, maybe a better idea is every time you want to show a notification, you just init a configuration object
I am sorry for this problem, just like I mentioned, this library is not fully tested, especially in multithread environment, it was written just in a short time, so this is possibility that it is not stable, but I will try to make it a full fledged UI Element, if you find the problem and a solution, please don't hesitate to submit a pull request.

**Comment by inatu** [comment]
``` swift
 func dismissNotificationWithCompletion(completion: (() -> Void)?) {
        if isDismissing && isShowing { return }
        isDismissing = true

        self.middleFrameChange()
        UIView.animateWithDuration(animateOutLength, animations: { () -> Void in
            self.animateOutFrameChange()
            }, completion: { (finished) -> Void in
                self.notificationWindow.hidden = true
                self.messageLabel = nil
                self.snapshotView = nil
                self.customView = nil

                self.isShowing = false
                self.isDismissing = false

                self.notificationLabelConfiguration = nil
                self.notificationCenterConfiguration = nil

                NSNotificationCenter.defaultCenter().removeObserver(self, name: UIApplicationDidChangeStatusBarOrientationNotification, object: nil)

                if let completion = completion {
                    completion()
                }
        })
    }

```

check this method, I will set the configuration object to nil every time the notification showing process is done, because I think the notification is showing in a very low frequency, and the configuration object is easy to setup, just like this demo, I set it in a single method

As for multithread environment, my thought is to think this notification centre as a time machine, when you want to display another notification, you call a class method, in this class method, it will check if the notification centre  is showing a notification, if it is, it will first cancel the notification, and then show the latest notification, but I think my implementation may have problem of replacing the old configuration object too early, and cause some problem, I will test this case tomorrow and try to fix it.

**Comment by inatu** [comment]
I think I will fix this bug tomorrow, if my ordinary work is not so busy, sorry, its 11pm in China, thanks for reporting it, I think tomorrow I will also update the read me to describe some feature I think will be added later, I really hope you all can contribute to this repo, after all, some need is related to the context of our application, but I think with extension feature of swift, we can build a powerful and flexible status bar notification element

**Comment by inatu** [comment]
@matiaskorhonen, I have added a notification queue to process multiple notification, and also expand the demo to show how it is like, please update to version 1.1.0 and check if it worked, thanks

**Comment by matiaskorhonen** [comment]
Thanks! Seems to work great now. I'll submit a new version of my app (http://ios.piranhas.co/) to iTunes Connect tomorrow (with `StatusBarNotificationCenter` instead of `CWStatusBarNotification`).
