### ISSUE TITLE
User interaction during notifications

### ISSUE THREAD

**Issue by matiaskorhonen** [36Kr-Mobile/StatusBarNotificationCenter#4]
Hi, I know you have “Let the users interact with the app during the notification is showing” in the upcoming features but I was wondering if there might be a workaround for this at the moment?

**Comment by inatu** [comment]
Hi, I have just added the support for user interaction, just like I said, I think this library is written with very much flexibility, because it can satisfy our own app's requirement, so there is not much motivation for me to add new features. You can check the latest commit to see how it is easy to add new functionality to this repo. I really recommend you take some time to learn the structure of this repo. I think with singleton design pattern and so little public interface, you can add new features freely without worrying other people who are using this library.
